### ISSUE TITLE
RTK title sounds incomplete

### ISSUE THREAD

**Issue by marvk** [tsudoko/kanjigrid#6]
https://github.com/tsudoko/kanjigrid/blob/9e3150ab868475fa017aeb43fd7bc349b7a78a71/data.py#L55

Right now it says "Remembering the Kanji volume". I think it should be either just "Remembering the Kanji" or something like "Remembering the Kanji volumes 1 and 3".

**Comment by tsudoko** [comment]
I changed it because "Group by Remembering the Kanji" seemed incomplete, less consistent with other titles and not descriptive enough, since it didn't explain if the kanji were about to be grouped by volume, by lesson, by page or not grouped at all. I agree it looks a bit weird though. I'll think about it.
